import { Offer } from '@/types/offer';

export const mockOffers: Offer[] = [
  {
    id: '1',
    title: 'Buy 2 Get 1 Free',
    description: 'Valid on all bakery items. Mix and match any three items from our fresh selection.',
    shopName: 'Sunrise Bakery',
    discount: '33% OFF',
    validUntil: '2026-06-15',
    locationId: 'downtown-austin',
  },
  {
    id: '2',
    title: 'Flat 20% Off on Groceries',
    description: 'Get 20% off on orders above $50. Fresh produce and daily essentials included.',
    shopName: 'GreenMart',
    discount: '20% OFF',
    validUntil: '2026-06-30',
    locationId: 'downtown-austin',
  },
  {
    id: '3',
    title: 'Weekend Coffee Special',
    description: 'Any large coffee for the price of a medium. Available Saturday and Sunday only.',
    shopName: 'Bean & Brew',
    discount: 'FREE UPGRADE',
    validUntil: '2026-06-08',
    locationId: 'south-congress',
  },
  {
    id: '4',
    title: 'Haircut + Beard Trim Combo',
    description: 'Complete grooming package at a special price. Walk-ins welcome.',
    shopName: 'Style Studio',
    discount: '$15 OFF',
    validUntil: '2026-07-01',
    locationId: 'south-congress',
  },
  {
    id: '5',
    title: 'Pizza Party Deal',
    description: 'Two large pizzas with two sides and drinks. Perfect for family gatherings.',
    shopName: 'Slice Heaven',
    discount: '25% OFF',
    validUntil: '2026-06-20',
    locationId: 'east-austin',
  },
  {
    id: '6',
    title: 'Summer Sale on Footwear',
    description: 'Up to 40% off on selected sneakers and sandals. Limited stock available.',
    shopName: 'StepUp Shoes',
    discount: '40% OFF',
    validUntil: '2026-08-01',
    locationId: 'east-austin',
  },
  {
    id: '7',
    title: 'Yoga Class Trial Pack',
    description: 'Three trial sessions for new members. All skill levels welcome.',
    shopName: 'ZenFit Studio',
    discount: '50% OFF',
    validUntil: '2026-06-25',
    locationId: 'domain-austin',
  },
  {
    id: '8',
    title: 'Electronics Clearance',
    description: 'Discounts on headphones, chargers, and phone accessories while stocks last.',
    shopName: 'TechHub',
    discount: '30% OFF',
    validUntil: '2026-06-18',
    locationId: 'domain-austin',
  },
];
